name: Handle Version Selection

on:
  issue_comment:
    types: [created, edited]

jobs:
  handle-version-selection:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Get PR details
        id: get-pr
        run: |
          PR_NUMBER="${{ github.event.issue.number }}"
          PR_TITLE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | \
            jq -r '.title')
          PR_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | \
            jq -r '.head.ref')
          echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
          echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT
          echo "PR branch: $PR_BRANCH"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-pr.outputs.pr_branch }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create or update changeset
        id: create-changeset
        run: |
          mkdir -p .changeset
          BUMP_TYPE=$(echo "${{ github.event.comment.body }}" | sed -n 's/\/changeset \([a-z]*\).*/\1/p' || echo "patch")
          CHANGESET_FILE=".changeset/pr-${{ github.event.issue.number }}.md"

          # Check if changeset already exists
          if [ -f "$CHANGESET_FILE" ]; then
            echo "Updating existing changeset file..."
            # Extract existing bump type if present
            EXISTING_BUMP=$(grep -o '"react-post-message": [a-z]*' "$CHANGESET_FILE" | cut -d' ' -f2 || echo "")
            if [ -n "$EXISTING_BUMP" ]; then
              BUMP_TYPE=$EXISTING_BUMP
            fi
          else
            echo "Creating new changeset file..."
          fi

          cat > "$CHANGESET_FILE" << EOF
          ---
          "react-post-message": $BUMP_TYPE
          ---

          ${{ steps.get-pr.outputs.pr_title }}
          EOF
          echo "changeset_file=$CHANGESET_FILE" >> $GITHUB_OUTPUT

      - name: Commit and push changeset
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${{ steps.create-changeset.outputs.changeset_file }}"
          git commit -m "chore: $([ -f "${{ steps.create-changeset.outputs.changeset_file }}" ] && echo "update" || echo "add") changeset for PR #${{ github.event.issue.number }}"
          git push origin ${{ steps.get-pr.outputs.pr_branch }} --force

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '✅ changeset updated successfully'
              })
            } catch (error) {
              console.error('Failed to create comment:', error)
              process.exit(1)
            }
