name: Handle Version Selection

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  debug:
    name: Debug Event
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: |
          echo "Event Type: ${{ github.event_name }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Is PR: ${{ github.event.issue.pull_request }}"
          echo "PR URL: ${{ github.event.issue.pull_request.url }}"

  handle-version:
    name: Handle Version Selection
    needs: debug
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get PR Details
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const prUrl = context.payload.issue.pull_request.url;
            console.log('Fetching PR details from:', prUrl);

            const { data: pr } = await github.request(prUrl);
            console.log('PR Base Branch:', pr.base.ref);

            return {
              base: pr.base.ref,
              head: pr.head.ref,
              number: pr.number
            }

      - name: Create Changeset
        if: steps.pr-details.outputs.base == 'develop'
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          TYPE=$(echo "$COMMENT_BODY" | awk '{print $2}')

          if [[ "$TYPE" =~ ^(major|minor|patch)$ ]]; then
            pnpm changeset add --$TYPE
            git add .changeset
            git commit -m "chore: add changeset for $TYPE update"
            git push origin HEAD
          else
            echo "Invalid version type: $TYPE"
            exit 1
          fi

      - name: Comment on PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const type = context.payload.comment.body.split(' ')[1];
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: `✅ ${type} 타입의 changeset이 생성되었습니다.`
            });
