name: Handle Version Selection

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: |
          echo "Event Type: ${{ github.event_name }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Is PR?: ${{ github.event.issue.pull_request != null }}"
          echo "PR Number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "PR URL: ${{ github.event.issue.pull_request.url }}"

  handle-version:
    needs: debug
    name: Handle Version Selection
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/changeset') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Handle Version Selection
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            console.log('Starting version selection handling...');

            try {
              const prUrl = context.payload.issue.pull_request.url;
              console.log('PR URL:', prUrl);
              
              // PR API URL에서 PR 정보 가져오기
              const { data: pullRequest } = await github.request(prUrl);
              console.log('Pull request data:', pullRequest);

              console.log('Pull request base branch:', pullRequest.base.ref);
              
              // develop 브랜치로의 PR인지 확인
              if (pullRequest.base.ref !== 'develop') {
                console.log('This workflow only runs on PRs targeting develop branch');
                return;
              }

              const comment = context.payload.comment;
              const versionTypes = ['major', 'minor', 'patch'];
              const commentBody = comment.body.trim().toLowerCase();
              
              console.log('Processing comment:', commentBody);

              if (!commentBody.startsWith('/changeset')) {
                console.log('Comment does not start with /changeset');
                return;
              }

              const type = commentBody.split(' ')[1];
              console.log('Version type:', type);
              
              if (!versionTypes.includes(type)) {
                console.log('Invalid version type');
                return;
              }

              // changeset 생성
              const exec = require('child_process').execSync;
              exec(`pnpm changeset add --${type}`);
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.name,
                body: `✅ ${type} 타입의 changeset이 생성되었습니다.`
              });
            } catch (error) {
              console.error('Error:', error);
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.name,
                body: `❌ changeset 생성 중 오류가 발생했습니다: ${error.message}`
              });
            }
