name: Handle Version Selection
on:
  issue_comment:
    types: [created, edited, deleted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pull_request_comment:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        if: contains(github.event.comment.body, '/changeset')
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const commentBody = context.payload.comment.body;
            await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: '✅ changeset success'
              });
