name: Handle Version Selection

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  debug_event:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Info
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Full event:', JSON.stringify(context, null, 2))

      - name: Comment on PR
        if: github.event.issue.pull_request && contains(github.event.comment.body, '/changeset')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ changeset success'
            })
