name: Handle Version Selection

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  handle_comment:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Create Changeset
        if: contains(github.event.comment.body, '/changeset')
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          BUMP_TYPE=$(echo "$COMMENT_BODY" | awk '{print $2}')
          if [ -z "$BUMP_TYPE" ]; then
            BUMP_TYPE="patch"
          fi

          echo "Creating changeset for $BUMP_TYPE bump"
          echo "---
          '@yoonseokgyu/react-post-message': $BUMP_TYPE
          ---

          PR #${{ github.event.issue.number }} - $(gh pr view ${{ github.event.issue.number }} --json title -q .title)
          " > .changeset/pr-${{ github.event.issue.number }}.md

      - name: Commit and Push Changeset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .changeset/
          git commit -m "docs: add changeset for PR #${{ github.event.issue.number }}"
          git push

      - name: Comment Success
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ changeset created successfully'
            })
