name: Handle Version Selection

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pull_request_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Event:', JSON.stringify(context.payload, null, 2))

      - name: Comment on PR
        if: contains(github.event.comment.body, '/changeset')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ changeset success'
            })
